### ISSUE TITLE
Could you tell me how to use splint.R?

### ISSUE THREAD

**Issue by fsnibs10** [amerlevede/splint#2]
Hi, 

I found some of my sequencing samples present "smiley pattern" by observing the read depth plot along chromosome.  In order to remove this bias for CNV detecting, I noticed that some people had used this method in their pulished paper, e. g. Duan et al, 2018 [The origin and adaptive evolution of domesticated populations of yeast from Far East Asia](https://www.nature.com/articles/s41467-018-05106-7).  
So I want to ask for you help about splint.R usage.  Many thanks!

**Comment by amerlevede** [comment]
Dear fsnibs10,

The .R file is a script you can run using the programming language R. You can find the list of command line variables inside the code with a short comment for context.
